Repository nix-community/rnix-parser, pull requests merged in 2022-07, with the labels that each got.

#91 Move to Rust 2021 (smaller)
  Cargo.toml
  flake.lock
Labels: enhancement

#89 refactor: get rid of smol-str dependency
  Cargo.lock
  Cargo.toml
  examples/list-fns.rs
  src/parser.rs
  src/tokenizer.rs
Labels: enhancement

#92 chore+refactor: upgrade rowan to v0.15
  Cargo.lock
  Cargo.toml
  examples/list-fns.rs
  src/lib.rs
  src/types.rs
Labels: enhancement, dependencies

#75 handle operator associavity
  src/parser.rs
  test_data/general/lists.expect
  test_data/general/operators.expect
  test_data/general/operators.nix
  test_data/parser/list/2.expect
Labels: bug

#119 avoid stack overflow
  src/parser.rs
Labels: bug
